server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/skytouchDatabase?verifyServerCertificate=false&useSSL=false
    username: admin
    password: admin
    driver:
      class: com.mysql.jdbc.Driver
  rabbitmq:
    host: rabbitmq
    port: 5673
    username: guest
    password: guest
    listener:
      type: direct
      direct:
        default-requeue-rejected: false